import datetime
import wx
import wx.grid
import re
import MySQLdb
import MySQLdb.cursors
import gettext
from ConnectDB import *

class NewStudent(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: NewStudent.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, wx.GetApp().TopWindow)
        self.label_24 = wx.StaticText(self, wx.ID_ANY, _("NEW STUDENT"))
        self.notebook_8 = wx.Notebook(self, wx.ID_ANY, style=0)
        self.notebook_8_pane_1 = wx.Panel(self.notebook_8, wx.ID_ANY)
        self.IDNumber = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("ID Number"))
        self.LastName = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Last Name"))
        self.FirstName = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("First Name"))
        self.MiddleName = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Middle Name"))
        self.sizer_6_staticbox = wx.StaticBox(self.notebook_8_pane_1, wx.ID_ANY, _("Student"))
        self.text_ctrl_1 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_2 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_4 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_3 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.label_3 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Birthdate"))
        
        self.label_5 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Gender"))
        self.label_6 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Nationality"))
        self.label_14 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Date Entered"))
        
        self.datepicker_ctrl_3 = wx.DatePickerCtrl(self.notebook_8_pane_1, wx.ID_ANY)
        
        self.combo_box_1 = wx.ComboBox(self.notebook_8_pane_1, wx.ID_ANY, choices=[_("Male"), _("Female")], style=wx.CB_DROPDOWN)
        self.combo_box_2 = wx.ComboBox(self.notebook_8_pane_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.datepicker_ctrl_4 = wx.DatePickerCtrl(self.notebook_8_pane_1, wx.ID_ANY)
        
        self.label_7 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Address"))
        self.label_8 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("City"))
        self.label_9 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Region"))
        self.label_10 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Country"))
        self.text_ctrl_6 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_7 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_8 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_9 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.label_11 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Telephone No."))
        self.label_12 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Cellphone No."))
        self.label_13 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Email Address"))
        self.text_ctrl_10 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_11 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_12 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.label_21 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Last Name"))
        self.label_22 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("First Name"))
        self.label_23 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Contact No."))
        self.sizer_16_staticbox = wx.StaticBox(self.notebook_8_pane_1, wx.ID_ANY, _("Guardian"))
        self.text_ctrl_15 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_16 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_17 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.static_line_1 = wx.StaticLine(self.notebook_8_pane_1, wx.ID_ANY)
        self.CreateStudent = wx.Button(self.notebook_8_pane_1, wx.ID_ANY, _("Create"))
        self.Bind(wx.EVT_BUTTON, self.create, self.CreateStudent)###
        self.__set_properties()
        self.__do_layout()

    def __set_properties(self):
        # begin wxGlade: NewStudent.__set_properties
        self.SetTitle(_("New Student"))
        self.label_24.SetMinSize((294, 28))
        self.label_24.SetFont(wx.Font(17, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.IDNumber.SetMinSize((110, 20))
        self.IDNumber.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.LastName.SetMinSize((170, 20))
        self.LastName.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.FirstName.SetMinSize((255, 20))
        self.FirstName.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.MiddleName.SetMinSize((170, 20))
        self.MiddleName.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_1.SetMinSize((110, 27))
        self.text_ctrl_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_2.SetMinSize((170, 27))
        self.text_ctrl_2.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_4.SetMinSize((255, 27))
        self.text_ctrl_4.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_3.SetMinSize((170, 27))
        self.text_ctrl_3.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_3.SetMinSize((110, 19))
        self.label_3.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        #self.label_4.SetMinSize((50, 19))
        #self.label_4.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_5.SetMinSize((120, 19))
        self.label_5.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_6.SetMinSize((150, 19))
        self.label_6.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_14.SetMinSize((110, 19))
        self.label_14.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        #self.label_15.SetMinSize((138, 19))
        #self.label_15.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.datepicker_ctrl_3.SetMinSize((110, 27))
        self.datepicker_ctrl_3.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        #self.text_ctrl_5.SetMinSize((50, 27))
        #self.text_ctrl_5.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_1.SetMinSize((120, 27))
        self.combo_box_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_1.SetSelection(-1)
        self.combo_box_2.SetMinSize((150, 27))
        self.combo_box_2.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.datepicker_ctrl_4.SetMinSize((110, 27))
        self.datepicker_ctrl_4.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        #self.combo_box_3.SetMinSize((145, 27))
        #self.combo_box_3.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        #self.combo_box_3.SetSelection(0)
        self.label_7.SetMinSize((255, 19))
        self.label_7.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_8.SetMinSize((150, 19))
        self.label_8.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_9.SetMinSize((150, 19))
        self.label_9.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_10.SetMinSize((56, 19))
        self.label_10.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_6.SetMinSize((255, 27))
        self.text_ctrl_6.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_7.SetMinSize((150, 27))
        self.text_ctrl_7.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_8.SetMinSize((150, 27))
        self.text_ctrl_8.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_9.SetMinSize((150, 27))
        self.text_ctrl_9.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_11.SetMinSize((110, 20))
        self.label_11.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_12.SetMinSize((170, 20))
        self.label_12.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_13.SetMinSize((255, 20))
        self.label_13.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_10.SetMinSize((110, 27))
        self.text_ctrl_10.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_11.SetMinSize((170, 27))
        self.text_ctrl_11.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_12.SetMinSize((255, 27))
        self.text_ctrl_12.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_21.SetMinSize((170, 19))
        self.label_21.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_22.SetMinSize((255, 19))
        self.label_22.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_23.SetMinSize((83, 19))
        self.label_23.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_15.SetMinSize((170, 27))
        self.text_ctrl_15.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_16.SetMinSize((255, 27))
        self.text_ctrl_16.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_17.SetMinSize((170, 27))
        self.text_ctrl_17.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))

    def __do_layout(self):
        # begin wxGlade: NewStudent.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_16_staticbox.Lower()
        sizer_16 = wx.StaticBoxSizer(self.sizer_16_staticbox, wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_6_staticbox.Lower()
        sizer_6 = wx.StaticBoxSizer(self.sizer_6_staticbox, wx.HORIZONTAL)
        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19.Add(self.label_24, 0, 0, 0)
        sizer_2.Add(sizer_19, 0, wx.EXPAND, 0)
        sizer_6.Add(self.IDNumber, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(self.LastName, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(self.FirstName, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(self.MiddleName, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_7.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_7.Add(self.text_ctrl_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_7.Add(self.text_ctrl_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_7.Add(self.text_ctrl_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_5.Add(sizer_7, 0, wx.EXPAND, 0)
        sizer_8.Add(self.label_3, 0, 0, 0)
        #sizer_8.Add(self.label_4, 0, 0, 0)
        sizer_8.Add(self.label_5, 0, 0, 0)
        sizer_8.Add(self.label_6, 0, 0, 0)
        sizer_8.Add(self.label_14, 0, 0, 0)
        #sizer_8.Add(self.label_15, 0, 0, 0)
        sizer_5.Add(sizer_8, 0, wx.EXPAND, 0)
        sizer_9.Add(self.datepicker_ctrl_3, 0, 0, 0)
        #sizer_9.Add(self.text_ctrl_5, 0, 0, 0)
        sizer_9.Add(self.combo_box_1, 0, 0, 0)
        sizer_9.Add(self.combo_box_2, 0, 0, 0)
        sizer_9.Add(self.datepicker_ctrl_4, 0, 0, 0)
        #sizer_9.Add(self.combo_box_3, 0, 0, 0)
        sizer_5.Add(sizer_9, 0, wx.EXPAND, 0)
        sizer_10.Add(self.label_7, 0, 0, 0)
        sizer_10.Add(self.label_8, 0, 0, 0)
        sizer_10.Add(self.label_9, 0, 0, 0)
        sizer_10.Add(self.label_10, 0, 0, 0)
        sizer_5.Add(sizer_10, 0, wx.EXPAND, 0)
        sizer_11.Add(self.text_ctrl_6, 0, 0, 0)
        sizer_11.Add(self.text_ctrl_7, 0, 0, 0)
        sizer_11.Add(self.text_ctrl_8, 0, 0, 0)
        sizer_11.Add(self.text_ctrl_9, 0, 0, 0)
        sizer_5.Add(sizer_11, 0, wx.EXPAND, 0)
        sizer_12.Add(self.label_11, 0, 0, 0)
        sizer_12.Add(self.label_12, 0, 0, 0)
        sizer_12.Add(self.label_13, 0, 0, 0)
        sizer_5.Add(sizer_12, 0, wx.EXPAND, 0)
        sizer_13.Add(self.text_ctrl_10, 0, 0, 0)
        sizer_13.Add(self.text_ctrl_11, 0, 0, 0)
        sizer_13.Add(self.text_ctrl_12, 0, 0, 0)
        sizer_5.Add(sizer_13, 0, wx.EXPAND, 0)
        sizer_16.Add(self.label_21, 0, 0, 0)
        sizer_16.Add(self.label_22, 0, 0, 0)
        sizer_16.Add(self.label_23, 0, 0, 0)
        sizer_5.Add(sizer_16, 0, wx.EXPAND, 0)
        sizer_17.Add(self.text_ctrl_15, 0, 0, 0)
        sizer_17.Add(self.text_ctrl_16, 0, 0, 0)
        sizer_17.Add(self.text_ctrl_17, 0, 0, 0)
        sizer_5.Add(sizer_17, 0, wx.EXPAND, 0)
        sizer_5.Add(self.static_line_1, 0, wx.TOP | wx.EXPAND, 10)
        sizer_5.Add(self.CreateStudent, 0, 0, 0)
        self.notebook_8_pane_1.SetSizer(sizer_5)
        self.notebook_8.AddPage(self.notebook_8_pane_1, _("Data"))
        sizer_2.Add(self.notebook_8, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()

    def create(self, event):
        ID= (self.text_ctrl_1.GetValue())
        LastName= (self.text_ctrl_2.GetValue())
        FirstName= (self.text_ctrl_4.GetValue())
        MiddleName= (self.text_ctrl_3.GetValue())
        BirthDate1= str(self.datepicker_ctrl_3.GetValue())
        m=re.search(r'.\S+',BirthDate1)####
        BirthDate= m.group()
        Gender= (self.combo_box_1.GetValue())
        Nationality= (self.combo_box_2.GetValue())
        Address= (self.text_ctrl_6.GetValue())
        City= (self.text_ctrl_7.GetValue())
        Region= (self.text_ctrl_8.GetValue())
        Country= (self.text_ctrl_9.GetValue())
        GLast= (self.text_ctrl_15.GetValue())
        GFirst= (self.text_ctrl_16.GetValue())
        GContactNum= (self.text_ctrl_17.GetValue())
        TelNum= (self.text_ctrl_10.GetValue())
        CellNum= (self.text_ctrl_11.GetValue())
        Email= (self.text_ctrl_12.GetValue())
		#Year= (self.combo_box_3.GetValue())
        YearEntered1= str(self.datepicker_ctrl_4.GetValue())
        n=re.search(r'.\S+',YearEntered1)####
        YearEntered= n.group()
        try:
            db = connectdb()
            cur = db.cursor()
            cur.execute("INSERT INTO Students (Student_ID, LastName, FirstName, MiddleName, BirthDate, Gender, Nationality, Address, City, Region, Country, Guardian_LastName, Guardian_FirstName, Guardian_Contactno, TelNum, CellNum, Email, Year_Entered) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", (ID, LastName, FirstName, MiddleName, BirthDate, Gender, Nationality, Address, City, Region, Country, GLast, GFirst, GContactNum, TelNum, CellNum, Email, YearEntered))
            db.commit()	
            cur.close()
            self.reload()
        except MySQLdb.IntegrityError:
            dlg = wx.MessageDialog(self,
                                  message='Duplicate ID: ID already registered on database',
                                  caption='A Message Box',
                                  style=wx.OK|wx.ICON_INFORMATION
                                  )
            dlg.ShowModal()
            dlg.Destroy()
		###grid_1.AppendRows(1)		
    def reload(self):       
        self.text_ctrl_1.Clear()
        self.text_ctrl_2.Clear()
        self.text_ctrl_4.Clear()
        self.text_ctrl_3.Clear()
        self.combo_box_1.Clear()
        self.combo_box_2.Clear()
        self.text_ctrl_6.Clear()
        self.text_ctrl_7.Clear()
        self.text_ctrl_8.Clear()
        self.text_ctrl_9.Clear()
        self.text_ctrl_15.Clear()
        self.text_ctrl_16.Clear()
        self.text_ctrl_17.Clear()
        self.text_ctrl_10.Clear()
        self.text_ctrl_11.Clear()
        self.text_ctrl_12.Clear()
         
		
class NewTeacher(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: NewTeacher.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, wx.GetApp().TopWindow)
        self.label_24 = wx.StaticText(self, wx.ID_ANY, _("NEW TEACHER"))
        self.notebook_8 = wx.Notebook(self, wx.ID_ANY, style=0)
        self.notebook_8_pane_1 = wx.Panel(self.notebook_8, wx.ID_ANY)
        self.IDNumber = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("ID Number"))
        self.LastName = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Last Name"))
        self.FirstName = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("First Name"))
        self.MiddleName = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Middle Name"))
        self.sizer_6_staticbox = wx.StaticBox(self.notebook_8_pane_1, wx.ID_ANY, _("Teacher"))
        self.text_ctrl_1 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_2 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_4 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_3 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.label_3 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Birthdate"))
        #self.label_4 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Age"))
        self.label_5 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Gender"))
        self.label_6 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Nationality"))
        self.label_14 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Date Entered"))
        self.datepicker_ctrl_1 = wx.DatePickerCtrl(self.notebook_8_pane_1, wx.ID_ANY)
        #self.text_ctrl_5 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.combo_box_1 = wx.ComboBox(self.notebook_8_pane_1, wx.ID_ANY, choices=[_("Male"), _("Female")], style=wx.CB_DROPDOWN)
        self.combo_box_2 = wx.ComboBox(self.notebook_8_pane_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.datepicker_ctrl_2 = wx.DatePickerCtrl(self.notebook_8_pane_1, wx.ID_ANY)
        self.label_7 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Address"))
        self.label_8 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("City"))
        self.label_9 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Region"))
        self.label_10 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Country"))
        self.text_ctrl_6 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_7 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_8 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_9 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.label_11 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Telephone No."))
        self.label_12 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Cellphone No."))
        self.label_13 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Email Address"))
        self.text_ctrl_10 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_11 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_12 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.static_line_1 = wx.StaticLine(self.notebook_8_pane_1, wx.ID_ANY)
        self.CreateStudent = wx.Button(self.notebook_8_pane_1, wx.ID_ANY, _("Create"))
        
        self.Bind(wx.EVT_BUTTON, self.create, self.CreateStudent)###
        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: NewTeacher.__set_properties
        self.SetTitle(_("New Teacher"))
        self.label_24.SetMinSize((155, 28))
        self.label_24.SetFont(wx.Font(17, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.IDNumber.SetMinSize((110, 20))
        self.IDNumber.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.LastName.SetMinSize((170, 20))
        self.LastName.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.FirstName.SetMinSize((255, 20))
        self.FirstName.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.MiddleName.SetMinSize((170, 20))
        self.MiddleName.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_1.SetMinSize((110, 27))
        self.text_ctrl_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_2.SetMinSize((170, 27))
        self.text_ctrl_2.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_4.SetMinSize((255, 27))
        self.text_ctrl_4.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_3.SetMinSize((170, 27))
        self.text_ctrl_3.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_3.SetMinSize((110, 19))
        self.label_3.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        #self.label_4.SetMinSize((50, 19))
        #self.label_4.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_5.SetMinSize((120, 19))
        self.label_5.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_6.SetMinSize((150, 19))
        self.label_6.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_14.SetMinSize((110, 19))
        self.label_14.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.datepicker_ctrl_1.SetMinSize((110, 27))
        self.datepicker_ctrl_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        #self.text_ctrl_5.SetMinSize((50, 27))
        #self.text_ctrl_5.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_1.SetMinSize((120, 27))
        self.combo_box_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_1.SetSelection(-1)
        self.combo_box_2.SetMinSize((150, 27))
        self.combo_box_2.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.datepicker_ctrl_2.SetMinSize((110, 27))
        self.datepicker_ctrl_2.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_7.SetMinSize((255, 19))
        self.label_7.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_8.SetMinSize((150, 19))
        self.label_8.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_9.SetMinSize((150, 19))
        self.label_9.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_10.SetMinSize((56, 19))
        self.label_10.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_6.SetMinSize((255, 27))
        self.text_ctrl_6.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_7.SetMinSize((150, 27))
        self.text_ctrl_7.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_8.SetMinSize((150, 27))
        self.text_ctrl_8.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_9.SetMinSize((150, 27))
        self.text_ctrl_9.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_11.SetMinSize((110, 20))
        self.label_11.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_12.SetMinSize((170, 20))
        self.label_12.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_13.SetMinSize((255, 20))
        self.label_13.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_10.SetMinSize((110, 27))
        self.text_ctrl_10.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_11.SetMinSize((170, 27))
        self.text_ctrl_11.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_12.SetMinSize((255, 27))
        self.text_ctrl_12.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: NewTeacher.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_6_staticbox.Lower()
        sizer_6 = wx.StaticBoxSizer(self.sizer_6_staticbox, wx.HORIZONTAL)
        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19.Add(self.label_24, 0, 0, 0)
        sizer_2.Add(sizer_19, 0, wx.EXPAND, 0)
        sizer_6.Add(self.IDNumber, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(self.LastName, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(self.FirstName, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(self.MiddleName, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_7.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_7.Add(self.text_ctrl_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_7.Add(self.text_ctrl_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_7.Add(self.text_ctrl_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_5.Add(sizer_7, 0, wx.EXPAND, 0)
        sizer_8.Add(self.label_3, 0, 0, 0)
        #sizer_8.Add(self.label_4, 0, 0, 0)
        sizer_8.Add(self.label_5, 0, 0, 0)
        sizer_8.Add(self.label_6, 0, 0, 0)
        sizer_8.Add(self.label_14, 0, 0, 0)
        sizer_5.Add(sizer_8, 0, wx.EXPAND, 0)
        sizer_9.Add(self.datepicker_ctrl_1, 0, 0, 0)
        #sizer_9.Add(self.text_ctrl_5, 0, 0, 0)
        sizer_9.Add(self.combo_box_1, 0, 0, 0)
        sizer_9.Add(self.combo_box_2, 0, 0, 0)
        sizer_9.Add(self.datepicker_ctrl_2, 0, 0, 0)
        sizer_5.Add(sizer_9, 0, wx.EXPAND, 0)
        sizer_10.Add(self.label_7, 0, 0, 0)
        sizer_10.Add(self.label_8, 0, 0, 0)
        sizer_10.Add(self.label_9, 0, 0, 0)
        sizer_10.Add(self.label_10, 0, 0, 0)
        sizer_5.Add(sizer_10, 0, wx.EXPAND, 0)
        sizer_11.Add(self.text_ctrl_6, 0, 0, 0)
        sizer_11.Add(self.text_ctrl_7, 0, 0, 0)
        sizer_11.Add(self.text_ctrl_8, 0, 0, 0)
        sizer_11.Add(self.text_ctrl_9, 0, 0, 0)
        sizer_5.Add(sizer_11, 0, wx.EXPAND, 0)
        sizer_12.Add(self.label_11, 0, 0, 0)
        sizer_12.Add(self.label_12, 0, 0, 0)
        sizer_12.Add(self.label_13, 0, 0, 0)
        sizer_5.Add(sizer_12, 0, wx.EXPAND, 0)
        sizer_13.Add(self.text_ctrl_10, 0, 0, 0)
        sizer_13.Add(self.text_ctrl_11, 0, 0, 0)
        sizer_13.Add(self.text_ctrl_12, 0, 0, 0)
        sizer_5.Add(sizer_13, 0, wx.EXPAND, 0)
        sizer_5.Add(self.static_line_1, 0, wx.TOP | wx.EXPAND, 10)
        sizer_5.Add(self.CreateStudent, 0, 0, 0)
        self.notebook_8_pane_1.SetSizer(sizer_5)
        self.notebook_8.AddPage(self.notebook_8_pane_1, _("Data"))
        sizer_2.Add(self.notebook_8, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade
    def create(self, event):
        ID= (self.text_ctrl_1.GetValue())
        LastName= (self.text_ctrl_2.GetValue())
        FirstName= (self.text_ctrl_4.GetValue())
        MiddleName= (self.text_ctrl_3.GetValue())
        BirthDate1= str(self.datepicker_ctrl_1.GetValue())
        m=re.search(r'.\S+',BirthDate1)####
        BirthDate= m.group()
        Gender= (self.combo_box_1.GetValue())
        Nationality= (self.combo_box_2.GetValue())
        Address= (self.text_ctrl_6.GetValue())
        City= (self.text_ctrl_7.GetValue())
        Region= (self.text_ctrl_8.GetValue())
        Country= (self.text_ctrl_9.GetValue())
        TelNum= (self.text_ctrl_10.GetValue())
        CellNum= (self.text_ctrl_11.GetValue())
        Email= (self.text_ctrl_12.GetValue())
		
        YearEntered1= str(self.datepicker_ctrl_2.GetValue())
        n=re.search(r'.\S+',BirthDate1)####
        YearEntered= n.group()

        try:
            db = connectdb()
            cur = db.cursor()
            cur.execute("INSERT INTO Teachers (Teachers_ID, LastName, FirstName, MiddleName, BirthDate, Gender, Nationality, Address, City, Region, Country, TelNum, CellNum, Email, Year_Entered) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", (ID, LastName, FirstName, MiddleName, BirthDate, Gender, Nationality, Address, City, Region, Country, TelNum, CellNum, Email, YearEntered))
            db.commit()	
            cur.close()
            self.reload()
        except MySQLdb.IntegrityError:
            dlg = wx.MessageDialog(self,
                                  message='Duplicate ID: ID already registered on database',
                                  caption='A Message Box',
                                  style=wx.OK|wx.ICON_INFORMATION
                                  )
            dlg.ShowModal()
            dlg.Destroy()

    def reload(self):       
        self.text_ctrl_1.Clear()
        self.text_ctrl_2.Clear()
        self.text_ctrl_4.Clear()
        self.text_ctrl_3.Clear()
        #self.combo_box_1.Clear()
        #self.combo_box_2.Clear()
        self.text_ctrl_6.Clear()
        self.text_ctrl_7.Clear()
        self.text_ctrl_8.Clear()
        self.text_ctrl_9.Clear()
        self.text_ctrl_10.Clear()
        self.text_ctrl_11.Clear()
        self.text_ctrl_12.Clear()
