import datetime
import wx
import wx.grid
import re
import MySQLdb
import MySQLdb.cursors
import gettext
from ConnectDB import *

class EditRecords(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: EditRecords.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, wx.GetApp().TopWindow)
        self.label_18 = wx.StaticText(self, wx.ID_ANY, _("ID Number"))
        self.text_ctrl_21 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.searchID = wx.Button(self, wx.ID_ANY, _("load"))
        self.notebook_8 = wx.Notebook(self, wx.ID_ANY, style=0)
        self.notebook_8_pane_1 = wx.Panel(self.notebook_8, wx.ID_ANY)
        self.IDNumber = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("ID Number"))
        self.LastName = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Last Name"))
        self.FirstName = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("First Name"))
        self.MiddleName = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Middle Name"))
        self.sizer_6_staticbox = wx.StaticBox(self.notebook_8_pane_1, wx.ID_ANY, _("Student"))
        self.text_ctrl_1 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_2 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_4 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_3 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.label_3 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Birthdate"))
        self.label_4 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Age"))
        self.label_5 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Gender"))
        self.label_6 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Nationality"))
        self.label_14 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Date Entered"))
        self.label_15 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Current Year/Grade"))
        self.text_ctrl_13 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_5 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.combo_box_1 = wx.ComboBox(self.notebook_8_pane_1, wx.ID_ANY, choices=[_("Male"), _("Female")], style=wx.CB_DROPDOWN)
        self.combo_box_2 = wx.ComboBox(self.notebook_8_pane_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.text_ctrl_14 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.combo_box_3 = wx.ComboBox(self.notebook_8_pane_1, wx.ID_ANY, choices=[_(""),_("Grade 1"), _("Grade 2"), _("Grade 3"), _("Grade 4"), _("Grade 5"), _("Grade 6"), _("HS 1"), _("HS 2"), _("HS 3"), _("HS 4")], style=wx.CB_DROPDOWN)
        self.label_7 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Address"))
        self.label_8 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("City"))
        self.label_9 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Region"))
        self.label_10 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Country"))
        self.text_ctrl_6 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_7 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_8 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_9 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.label_11 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Telephone No."))
        self.label_12 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Cellphone No."))
        self.label_13 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Email Address"))
        self.text_ctrl_10 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_11 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_12 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.label_21 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Last Name"))
        self.label_22 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("First Name"))
        self.label_23 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Contact No."))
        self.sizer_16_staticbox = wx.StaticBox(self.notebook_8_pane_1, wx.ID_ANY, _("Guardian"))
        self.text_ctrl_15 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_16 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.text_ctrl_17 = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.static_line_1 = wx.StaticLine(self.notebook_8_pane_1, wx.ID_ANY)
        self.button_edit = wx.Button(self.notebook_8_pane_1, wx.ID_ANY, _("Edit"))
        self.button_3 = wx.Button(self.notebook_8_pane_1, wx.ID_ANY, _("Save"))
        self.notebook_8_pane_2 = wx.Panel(self.notebook_8, wx.ID_ANY)
        self.SchoolYear = wx.StaticText(self.notebook_8_pane_2, wx.ID_ANY, _("School Year"))
        self.combo_box_8 = wx.ComboBox(self.notebook_8_pane_2, wx.ID_ANY, choices=[_(""),_("2013-2014"),_("2014-2015"),_("2015-2016"),_("2016-2017"),_("2017-2018"),_("2018-2019"),_("2019-2020"),_("2020-2021"),_("2021-2022"),_("2023-2024"),], style=wx.CB_DROPDOWN | wx.CB_DROPDOWN | wx.CB_READONLY)
        self.label_2 = wx.StaticText(self.notebook_8_pane_2, wx.ID_ANY, _("Year/Grade"))
        self.combo_box_5 = wx.ComboBox(self.notebook_8_pane_2, wx.ID_ANY, choices=[_(""),_("Year1"), _("Year2"), _("Year3"), _("Year4"), _("Grade1"), _("Grade2"), _("Grade3"), _("Grade4"), _("Grade5"), _("Grade6")], style=wx.CB_DROPDOWN | wx.CB_DROPDOWN | wx.CB_READONLY)
        self.label_16 = wx.StaticText(self.notebook_8_pane_2, wx.ID_ANY, _("Section"))
        self.combo_box_6 = wx.ComboBox(self.notebook_8_pane_2, wx.ID_ANY, choices=[_(""),_("Section1"), _("Section2"), _("Section3"), _("Section4")], style=wx.CB_DROPDOWN | wx.CB_DROPDOWN | wx.CB_READONLY)
        self.label_17 = wx.StaticText(self.notebook_8_pane_2, wx.ID_ANY, _("Adviser"))
        self.combo_box_7 = wx.ComboBox(self.notebook_8_pane_2, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_DROPDOWN | wx.CB_READONLY)
        self.Enroll = wx.Button(self.notebook_8_pane_2, wx.ID_ANY, _("Enroll"))
        self.DeleteRecord = wx.Button(self.notebook_8_pane_2, wx.ID_ANY, _("Delete"))
        self.static_line_2 = wx.StaticLine(self.notebook_8_pane_2, wx.ID_ANY, style=wx.LI_VERTICAL)
        self.panel_2 = wx.Panel(self.notebook_8_pane_2, wx.ID_ANY)
        self.grid_2 = wx.grid.Grid(self.panel_2, wx.ID_ANY, size=(1, 1))
        self.notebook_8_pane_3 = wx.Panel(self.notebook_8, wx.ID_ANY)
        self.SchoolYear_copy = wx.StaticText(self.notebook_8_pane_3, wx.ID_ANY, _("School Year"))
        self.combo_box_8_copy = wx.ComboBox(self.notebook_8_pane_3, wx.ID_ANY, choices=[_("2012-2013"), _("2013-2014"), _("2014-2015"), _("2015-2016"), _("2016-2017"), _("2017-2018"), _("2018-2019")], style=wx.CB_DROPDOWN | wx.CB_DROPDOWN)
        self.Year = wx.StaticText(self.notebook_8_pane_3, wx.ID_ANY, _("Year"))
        self.combo_box_8_copy_1 = wx.ComboBox(self.notebook_8_pane_3, wx.ID_ANY, choices=[_(""),_("Year1"), _("Year2"), _("Year3"), _("Year4"), _("Grade1"), _("Grade2"), _("Grade3"), _("Grade4"), _("Grade5"), _("Grade6")], style=wx.CB_DROPDOWN | wx.CB_DROPDOWN)
        self.Enroll_copy = wx.Button(self.notebook_8_pane_3, wx.ID_ANY, _("Load"))
        self.static_line_2_copy = wx.StaticLine(self.notebook_8_pane_3, wx.ID_ANY, style=wx.LI_VERTICAL)
        self.panel_2_copy = wx.Panel(self.notebook_8_pane_3, wx.ID_ANY)
        self.grid_2_copy = wx.grid.Grid(self.panel_2_copy, wx.ID_ANY, size=(1, 1))
        #self.notebook_8_pane_4 = wx.Panel(self.notebook_8, wx.ID_ANY)
        #self.notebook_8_pane_5 = wx.Panel(self.notebook_8, wx.ID_ANY)
        #self.notebook_8_pane_6 = wx.Panel(self.notebook_8, wx.ID_ANY)
		
		###
        self.Bind(wx.EVT_BUTTON, self.load, self.searchID)###################
        self.Bind(wx.EVT_BUTTON, self.edit, self.button_edit)
        self.Bind(wx.EVT_BUTTON, self.save, self.button_3)
        self.Bind(wx.EVT_BUTTON, self.enroll1, self.Enroll)
        self.Bind(wx.EVT_BUTTON, self.delete1, self.DeleteRecord)
        self.Bind(wx.EVT_BUTTON, self.loadgrades, self.Enroll_copy)		
		
        self.__set_properties()
        self.__do_layout()

    def __set_properties(self):
        # begin wxGlade: EditRecords.__set_properties
        self.SetTitle(_("Edit Records"))
        self.label_18.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.IDNumber.SetMinSize((110, 20))
        self.IDNumber.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.LastName.SetMinSize((170, 20))
        self.LastName.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.FirstName.SetMinSize((255, 20))
        self.FirstName.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.MiddleName.SetMinSize((170, 20))
        self.MiddleName.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_1.SetMinSize((110, 27))
        self.text_ctrl_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_1.Enable(False)
        self.text_ctrl_1.SetFocus()
        self.text_ctrl_2.SetMinSize((170, 27))
        self.text_ctrl_2.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_2.Enable(False)
        self.text_ctrl_2.SetFocus()
        self.text_ctrl_4.SetMinSize((255, 27))
        self.text_ctrl_4.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_4.Enable(False)
        self.text_ctrl_4.SetFocus()
        self.text_ctrl_3.SetMinSize((170, 27))
        self.text_ctrl_3.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_3.Enable(False)
        self.text_ctrl_3.SetFocus()
        self.label_3.SetMinSize((110, 19))
        self.label_3.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_4.SetMinSize((50, 19))
        self.label_4.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_5.SetMinSize((120, 19))
        self.label_5.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_6.SetMinSize((150, 19))
        self.label_6.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_14.SetMinSize((110, 19))
        self.label_14.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_15.SetMinSize((138, 19))
        self.label_15.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_13.SetMinSize((110, 27))
        self.text_ctrl_13.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_13.Enable(False)
        self.text_ctrl_5.SetMinSize((50, 27))
        self.text_ctrl_5.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_5.Enable(False)
        self.combo_box_1.SetMinSize((120, 27))
        self.combo_box_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_1.Enable(False)
        self.combo_box_1.SetSelection(-1)
        self.combo_box_2.SetMinSize((150, 27))
        self.combo_box_2.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_2.Enable(False)
        self.text_ctrl_14.SetMinSize((110, 27))
        self.text_ctrl_14.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_14.Enable(False)
        self.combo_box_3.SetMinSize((145, 27))
        self.combo_box_3.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_3.Enable(False)
        self.combo_box_3.SetSelection(0)
        self.label_7.SetMinSize((255, 19))
        self.label_7.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_8.SetMinSize((150, 19))
        self.label_8.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_9.SetMinSize((150, 19))
        self.label_9.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_10.SetMinSize((56, 19))
        self.label_10.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_6.SetMinSize((255, 27))
        self.text_ctrl_6.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_6.Enable(False)
        self.text_ctrl_7.SetMinSize((150, 27))
        self.text_ctrl_7.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_7.Enable(False)
        self.text_ctrl_8.SetMinSize((150, 27))
        self.text_ctrl_8.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_8.Enable(False)
        self.text_ctrl_9.SetMinSize((150, 27))
        self.text_ctrl_9.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_9.Enable(False)
        self.label_11.SetMinSize((110, 20))
        self.label_11.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_12.SetMinSize((170, 20))
        self.label_12.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_13.SetMinSize((255, 20))
        self.label_13.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_10.SetMinSize((110, 27))
        self.text_ctrl_10.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_10.Enable(False)
        self.text_ctrl_11.SetMinSize((170, 27))
        self.text_ctrl_11.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_11.Enable(False)
        self.text_ctrl_12.SetMinSize((255, 27))
        self.text_ctrl_12.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_12.Enable(False)
        self.label_21.SetMinSize((170, 20))
        self.label_21.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_22.SetMinSize((255, 19))
        self.label_22.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_23.SetMinSize((170, 20))
        self.label_23.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_15.SetMinSize((170, 27))
        self.text_ctrl_15.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_15.Enable(False)
        self.text_ctrl_16.SetMinSize((255, 27))
        self.text_ctrl_16.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_16.Enable(False)
        self.text_ctrl_17.SetMinSize((170, 27))
        self.text_ctrl_17.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.text_ctrl_17.Enable(False)
        self.button_edit.Enable(False)
        self.button_3.Enable(False)
        self.SchoolYear.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_8.SetMinSize((130, 27))
        self.combo_box_8.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_8.SetSelection(-1)
        self.label_2.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_5.SetMinSize((130, 27))
        self.combo_box_5.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_5.SetSelection(0)
        self.label_16.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_6.SetMinSize((130, 27))
        self.combo_box_6.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_6.SetSelection(-1)
        self.label_17.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_7.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.static_line_2.SetMinSize((25, 340))
        self.grid_2.CreateGrid(50, 4)
        self.grid_2.SetColLabelValue(0, _("School Year"))
        self.grid_2.SetColLabelValue(1, _("Year/Grade"))
        self.grid_2.SetColLabelValue(2, _("Section"))
        self.grid_2.SetColLabelValue(3, _("Adviser"))
        self.SchoolYear_copy.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_8_copy.SetMinSize((130, 27))
        self.combo_box_8_copy.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_8_copy.SetSelection(-1)
        self.Year.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_8_copy_1.SetMinSize((130, 27))
        self.combo_box_8_copy_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.combo_box_8_copy_1.SetSelection(-1)
        self.static_line_2_copy.SetMinSize((25, 340))
        self.grid_2_copy.CreateGrid(15, 6)
        self.grid_2_copy.SetRowLabelSize(30)
        self.grid_2_copy.SetColLabelSize(30)
        self.grid_2_copy.SetColLabelValue(0, _("Subject"))
        self.grid_2_copy.SetColLabelValue(1, _("1st Term"))
        self.grid_2_copy.SetColLabelValue(2, _("2nd Term"))
        self.grid_2_copy.SetColLabelValue(3, _("3rd Term"))
        self.grid_2_copy.SetColLabelValue(4, _("4th Term"))
        self.grid_2_copy.SetColLabelValue(5, _("General Average"))
        self.grid_2_copy.SetColSize(5, 110)

    def __do_layout(self):
        # begin wxGlade: EditRecords.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_28_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_30_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_29_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_28 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_30 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_29 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_16_staticbox.Lower()
        sizer_16 = wx.StaticBoxSizer(self.sizer_16_staticbox, wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_6_staticbox.Lower()
        sizer_6 = wx.StaticBoxSizer(self.sizer_6_staticbox, wx.HORIZONTAL)
        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19.Add(self.label_18, 0, 0, 0)
        sizer_19.Add(self.text_ctrl_21, 0, 0, 0)
        sizer_19.Add(self.searchID, 0, 0, 0)
        sizer_2.Add(sizer_19, 0, wx.EXPAND, 0)
        sizer_6.Add(self.IDNumber, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(self.LastName, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(self.FirstName, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(self.MiddleName, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_7.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_7.Add(self.text_ctrl_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_7.Add(self.text_ctrl_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_7.Add(self.text_ctrl_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_5.Add(sizer_7, 0, wx.EXPAND, 0)
        sizer_8.Add(self.label_3, 0, 0, 0)
        sizer_8.Add(self.label_4, 0, 0, 0)
        sizer_8.Add(self.label_5, 0, 0, 0)
        sizer_8.Add(self.label_6, 0, 0, 0)
        sizer_8.Add(self.label_14, 0, 0, 0)
        sizer_8.Add(self.label_15, 0, 0, 0)
        sizer_5.Add(sizer_8, 0, wx.EXPAND, 0)
        sizer_9.Add(self.text_ctrl_13, 0, 0, 0)
        sizer_9.Add(self.text_ctrl_5, 0, 0, 0)
        sizer_9.Add(self.combo_box_1, 0, 0, 0)
        sizer_9.Add(self.combo_box_2, 0, 0, 0)
        sizer_9.Add(self.text_ctrl_14, 0, 0, 0)
        sizer_9.Add(self.combo_box_3, 0, 0, 0)
        sizer_5.Add(sizer_9, 0, wx.EXPAND, 0)
        sizer_10.Add(self.label_7, 0, 0, 0)
        sizer_10.Add(self.label_8, 0, 0, 0)
        sizer_10.Add(self.label_9, 0, 0, 0)
        sizer_10.Add(self.label_10, 0, 0, 0)
        sizer_5.Add(sizer_10, 0, wx.EXPAND, 0)
        sizer_11.Add(self.text_ctrl_6, 0, 0, 0)
        sizer_11.Add(self.text_ctrl_7, 0, 0, 0)
        sizer_11.Add(self.text_ctrl_8, 0, 0, 0)
        sizer_11.Add(self.text_ctrl_9, 0, 0, 0)
        sizer_5.Add(sizer_11, 0, wx.EXPAND, 0)
        sizer_12.Add(self.label_11, 0, 0, 0)
        sizer_12.Add(self.label_12, 0, 0, 0)
        sizer_12.Add(self.label_13, 0, 0, 0)
        sizer_5.Add(sizer_12, 0, wx.EXPAND, 0)
        sizer_13.Add(self.text_ctrl_10, 0, 0, 0)
        sizer_13.Add(self.text_ctrl_11, 0, 0, 0)
        sizer_13.Add(self.text_ctrl_12, 0, 0, 0)
        sizer_5.Add(sizer_13, 0, wx.EXPAND, 0)
        sizer_16.Add(self.label_21, 0, 0, 0)
        sizer_16.Add(self.label_22, 0, 0, 0)
        sizer_16.Add(self.label_23, 0, 0, 0)
        sizer_5.Add(sizer_16, 0, wx.EXPAND, 0)
        sizer_17.Add(self.text_ctrl_15, 0, 0, 0)
        sizer_17.Add(self.text_ctrl_16, 0, 0, 0)
        sizer_17.Add(self.text_ctrl_17, 0, 0, 0)
        sizer_5.Add(sizer_17, 0, wx.EXPAND, 0)
        sizer_5.Add(self.static_line_1, 0, wx.TOP | wx.EXPAND, 10)
        sizer_5.Add(self.button_edit, 0, 0, 0)
        sizer_5.Add(self.button_3, 0, 0, 0)
        self.notebook_8_pane_1.SetSizer(sizer_5)
        sizer_29.Add(self.SchoolYear, 0, 0, 0)
        sizer_29.Add(self.combo_box_8, 0, 0, 0)
        sizer_29.Add((20, 5), 0, 0, 0)
        sizer_29.Add(self.label_2, 0, 0, 0)
        sizer_29.Add(self.combo_box_5, 0, 0, 0)
        sizer_29.Add((20, 5), 0, 0, 0)
        sizer_29.Add(self.label_16, 0, 0, 0)
        sizer_29.Add(self.combo_box_6, 0, 0, 0)
        sizer_29.Add((20, 5), 0, 0, 0)
        sizer_29.Add(self.label_17, 0, 0, 0)
        sizer_29.Add(self.combo_box_7, 0, 0, 0)
        sizer_29.Add((20, 5), 0, 0, 0)
        sizer_29.Add(self.Enroll, 0, 0, 0)
        sizer_29.Add(self.DeleteRecord, 0, 0, 0)
        sizer_28.Add(sizer_29, 0, wx.EXPAND, 0)
        sizer_28.Add(self.static_line_2, 0, wx.EXPAND, 0)
        sizer_30.Add(self.grid_2, 1, wx.EXPAND, 0)
        self.panel_2.SetSizer(sizer_30)
        sizer_28.Add(self.panel_2, 1, wx.EXPAND, 0)
        self.notebook_8_pane_2.SetSizer(sizer_28)
        sizer_29_copy.Add(self.SchoolYear_copy, 0, 0, 0)
        sizer_29_copy.Add(self.combo_box_8_copy, 0, 0, 0)
        sizer_29_copy.Add(self.Year, 0, 0, 0)
        sizer_29_copy.Add(self.combo_box_8_copy_1, 0, 0, 0)
        sizer_29_copy.Add(self.Enroll_copy, 0, 0, 0)
        sizer_28_copy.Add(sizer_29_copy, 0, wx.EXPAND, 0)
        sizer_28_copy.Add(self.static_line_2_copy, 0, wx.EXPAND, 0)
        sizer_30_copy.Add(self.grid_2_copy, 1, wx.EXPAND, 0)
        self.panel_2_copy.SetSizer(sizer_30_copy)
        sizer_28_copy.Add(self.panel_2_copy, 1, wx.EXPAND, 0)
        self.notebook_8_pane_3.SetSizer(sizer_28_copy)
        self.notebook_8.AddPage(self.notebook_8_pane_1, _("Student Data"))
        self.notebook_8.AddPage(self.notebook_8_pane_2, _("Class Records"))
        self.notebook_8.AddPage(self.notebook_8_pane_3, _("Grades"))
        #self.notebook_8.AddPage(self.notebook_8_pane_4, _("Medical History"))
        #self.notebook_8.AddPage(self.notebook_8_pane_5, _("Discipline Records"))
        #self.notebook_8.AddPage(self.notebook_8_pane_6, _("Clinic Records"))
        sizer_2.Add(self.notebook_8, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
 
    def load(self,event):
        try:
            ID= (self.text_ctrl_21.GetValue())
            db = connectdb()
            cur = db.cursor()
            cur.execute("SELECT * FROM Students WHERE Student_ID="+"'" + ID + "'")
            rows=cur.fetchall()
            i=0
            for r in rows:
                r
            self.reload()
            x=Age(str(r[4]))
            self.text_ctrl_1.SetValue(str(r[0]))
            self.text_ctrl_2.SetValue(str(r[1]))
            self.text_ctrl_4.SetValue(str(r[2]))
            self.text_ctrl_3.SetValue(str(r[3]))
            self.text_ctrl_13.SetValue(str(r[4]))
            self.text_ctrl_5.SetValue(str(x))
            self.combo_box_1.SetValue(str(r[5]))
            self.combo_box_2.SetValue(str(r[6]))		
            self.text_ctrl_6.SetValue(str(r[7]))
            self.text_ctrl_7.SetValue(str(r[8]))
            self.text_ctrl_8.SetValue(str(r[9]))
            self.text_ctrl_9.SetValue(str(r[10]))
            self.text_ctrl_15.SetValue(str(r[11]))
            self.text_ctrl_16.SetValue(str(r[12]))
            self.text_ctrl_17.SetValue(str(r[13]))
            self.text_ctrl_10.SetValue(str(r[14]))
            self.text_ctrl_11.SetValue(str(r[15]))
            self.text_ctrl_12.SetValue(str(r[16]))
            self.text_ctrl_14.SetValue(str(r[18]))
            self.text_ctrl_1.Enable(False)
            self.text_ctrl_2.Enable(False)
            self.text_ctrl_4.Enable(False)
            self.text_ctrl_3.Enable(False)
            self.text_ctrl_13.Enable(False)
            self.text_ctrl_5.Enable(False)
            self.combo_box_1.Enable(False)
            self.combo_box_2.Enable(False)
            self.text_ctrl_14.Enable(False)
            self.combo_box_3.Enable(False)
            self.text_ctrl_6.Enable(False)
            self.text_ctrl_7.Enable(False)
            self.text_ctrl_8.Enable(False)
            self.text_ctrl_9.Enable(False)
            self.text_ctrl_10.Enable(False)
            self.text_ctrl_11.Enable(False)
            self.text_ctrl_12.Enable(False)
            self.text_ctrl_15.Enable(False)
            self.text_ctrl_16.Enable(False)
            self.text_ctrl_17.Enable(False)
            self.button_edit.Enable(True)
            self.button_3.Enable(False)
            self.refreshclass() ##load class records
        except UnboundLocalError:
            dlg = wx.MessageDialog(self,
                                  message='ID not found on database',
                                  caption='A Message Box',
                                  style=wx.OK|wx.ICON_INFORMATION
                                  )
            dlg.ShowModal()
            dlg.Destroy()	
    def edit(self,event):
        
        self.text_ctrl_2.Enable(True)
        self.text_ctrl_4.Enable(True)
        self.text_ctrl_3.Enable(True)
        self.text_ctrl_13.Enable(True)
        self.text_ctrl_5.Enable(False)
        self.combo_box_1.Enable(True)
        self.combo_box_2.Enable(True)
        self.text_ctrl_14.Enable(True)
        self.combo_box_3.Enable(True)
        self.text_ctrl_6.Enable(True)
        self.text_ctrl_7.Enable(True)
        self.text_ctrl_8.Enable(True)
        self.text_ctrl_9.Enable(True)
        self.text_ctrl_10.Enable(True)
        self.text_ctrl_11.Enable(True)
        self.text_ctrl_12.Enable(True)
        self.text_ctrl_15.Enable(True)
        self.text_ctrl_16.Enable(True)
        self.text_ctrl_17.Enable(True)
        self.button_edit.Enable(False)
        self.button_3.Enable(True)
    def save(self,event):
        ID= (self.text_ctrl_1.GetValue())
        LastName= (self.text_ctrl_2.GetValue())
        FirstName= (self.text_ctrl_4.GetValue())
        MiddleName= (self.text_ctrl_3.GetValue())
        BirthDate1= str(self.text_ctrl_13.GetValue())
        m=re.search(r'.\S+',BirthDate1)####
        BirthDate= m.group()
        Gender= (self.combo_box_1.GetValue())
        Nationality= (self.combo_box_2.GetValue())
        Address= (self.text_ctrl_6.GetValue())
        City= (self.text_ctrl_7.GetValue())
        Region= (self.text_ctrl_8.GetValue())
        Country= (self.text_ctrl_9.GetValue())
        GLast= (self.text_ctrl_15.GetValue())
        GFirst= (self.text_ctrl_16.GetValue())
        GContactNum= (self.text_ctrl_17.GetValue())
        TelNum= (self.text_ctrl_10.GetValue())
        CellNum= (self.text_ctrl_11.GetValue())
        Email= (self.text_ctrl_12.GetValue())
        Year= (self.combo_box_3.GetValue())
        YearEntered1= str(self.text_ctrl_14.GetValue())
        n=re.search(r'.\S+',YearEntered1)####
        YearEntered= n.group()
        db = connectdb()
        cur = db.cursor()
        cur.execute("""
			UPDATE Students 
			SET LastName=%s, FirstName=%s, MiddleName=%s, BirthDate=%s, Gender=%s, Nationality=%s, Address=%s, City=%s, Region=%s, Country=%s, Guardian_LastName=%s, Guardian_FirstName=%s, Guardian_Contactno=%s, TelNum=%s, CellNum=%s, Email=%s, Year=%s, Year_Entered=%s 
			WHERE Student_ID=%s""",(LastName, FirstName, MiddleName, BirthDate, Gender, Nationality, Address, City, Region, Country, GLast, GFirst, GContactNum, TelNum, CellNum, Email, Year, YearEntered, ID))
        db.commit()		
        cur.close()
        self.text_ctrl_1.Enable(False)
        self.text_ctrl_2.Enable(False)
        self.text_ctrl_4.Enable(False)
        self.text_ctrl_3.Enable(False)
        self.text_ctrl_13.Enable(False)
        self.text_ctrl_5.Enable(False)
        self.combo_box_1.Enable(False)
        self.combo_box_2.Enable(False)
        self.text_ctrl_14.Enable(False)
        self.combo_box_3.Enable(False)
        self.text_ctrl_6.Enable(False)
        self.text_ctrl_7.Enable(False)
        self.text_ctrl_8.Enable(False)
        self.text_ctrl_9.Enable(False)
        self.text_ctrl_10.Enable(False)
        self.text_ctrl_11.Enable(False)
        self.text_ctrl_12.Enable(False)
        self.text_ctrl_15.Enable(False)
        self.text_ctrl_16.Enable(False)
        self.text_ctrl_17.Enable(False)
        self.button_edit.Enable(True)
        self.button_3.Enable(False)
    def enroll1(self,event):		
        ID= (self.text_ctrl_1.GetValue())
        SchoolYear= (self.combo_box_8.GetValue())
        Year= (self.combo_box_5.GetValue())
        Section= (self.combo_box_6.GetValue())
        Adviser= (self.combo_box_7.GetValue())
        if Adviser== "":
            db = connectdb()
            cur = db.cursor()
            cur.execute("INSERT INTO ClassRecords (SchoolYear, Year, Section, Students_Student_ID, Teachers_Teachers_ID) VALUES (%s, %s, %s, %s, NULL)", (SchoolYear, Year, Section, ID))
            db.commit()		
            cur.close()
        else:
            string=str(self.combo_box_7.GetValue())
            mylist= string.split(',')
            print mylist
            db = connectdb()
            cur1=db.cursor()
            cur1.execute("SELECT Teachers_ID FROM Teachers WHERE LastName= %s AND FirstName= %s", (mylist[0],mylist[1]))
            x=cur1.fetchall()
            for i in x:
			   i
            Adviser1= str(i[0])
            cur = db.cursor()
            cur.execute("INSERT INTO ClassRecords (SchoolYear, Year, Section, Students_Student_ID, Teachers_Teachers_ID) VALUES (%s, %s, %s, %s, %s)", (SchoolYear, Year, Section, ID, Adviser1))
            db.commit()		
            cur.close()
        self.refreshclass()
    def refreshclass(self):


        self.grid_2.ClearGrid()
        ID= (self.text_ctrl_1.GetValue())
        db = connectdb()
        cur = db.cursor()
        cur.execute("SELECT SchoolYear, Year, Section, Teachers_Teachers_ID FROM ClassRecords where Students_Student_ID="+"'" + ID + "'")
        rows=cur.fetchall()
       
        for i in range (0,len(rows)):
            for j in range(0,4):
                cell = rows[i]
                self.grid_2.SetCellValue(i,j,str(cell[j]))
        
        cur1=db.cursor()
        cur1.execute("SELECT CONCAT(LastName, ',' , FirstName) FROM Teachers")
        
        x=[]
        index=0
        all=cur1.fetchall()
			
        while index<len(all):
            x.append(all[index][0])
            index=index+1
        self.combo_box_7.SetItems(x)
    def delete1(self,event):
        ID= (self.text_ctrl_1.GetValue())
        SchoolYear= (self.combo_box_8.GetValue())
        db = connectdb()
        cur = db.cursor()
        cur.execute("DELETE FROM ClassRecords WHERE Students_Student_ID= %s AND SchoolYear= %s", (ID, SchoolYear))
        db.commit()		
        cur.close()
        self.refreshclass()
		
    def reload(self):
        self.text_ctrl_21.Clear()
        self.text_ctrl_1.Clear()
        self.text_ctrl_2.Clear()
        self.text_ctrl_4.Clear()
        self.text_ctrl_3.Clear()
        self.text_ctrl_13.Clear()
        self.text_ctrl_5.Clear()
        self.combo_box_1.Clear()
        self.combo_box_2.Clear()
        self.text_ctrl_6.Clear()
        self.text_ctrl_7.Clear()
        self.text_ctrl_8.Clear()
        self.text_ctrl_9.Clear()
        self.text_ctrl_15.Clear()
        self.text_ctrl_16.Clear()
        self.text_ctrl_17.Clear()
        self.text_ctrl_10.Clear()
        self.text_ctrl_11.Clear()
        self.text_ctrl_12.Clear()
        self.combo_box_3.Clear()
        #self.combo_box_8.Clear()
        #self.combo_box_5.Clear()
        #self.combo_box_6.Clear()
        self.combo_box_7.Clear()
        self.text_ctrl_14.Clear()

    def loadgrades(self,event):
        ID= (self.text_ctrl_1.GetValue())
        SY= (self.combo_box_8_copy.GetValue())
        Year= (self.combo_box_8_copy_1.GetValue())    
        db = connectdb()
        cur = db.cursor()
        cur.execute("SELECT Subjects FROM Curriculum WHERE SchoolYear=%s AND Year=%s",(SY,Year))
        y=[]
        index=0
        all=cur.fetchall()
			
        while index<len(all):
            y.append(all[index][0])
            index=index+1
        g=0
        q=0
        for z in range(0,len(y)):        
            self.grid_2_copy.SetCellValue(g,0,str(y[q]))		
            g=g+1
            q=q+1
        n=0
        x=0

        for w in range(0,len(y)):
            cur.execute("SELECT Subject_Grade FROM Grades WHERE Subject_Name= %s AND Students_Student_ID= %s AND SchoolYear=%s AND Grading='1st'",(y[n],ID,SY))
            rows=cur.fetchall()

            if len(rows) < 1:
                null=""
                self.grid_2_copy.SetCellValue(x,1,null)
            else:
                for i in rows:
                    i

                self.grid_2_copy.SetCellValue(x,1,str(i[0]))
            x=x+1
            n=n+1
        n=0
        x=0

        for w in range(0,len(y)):
            cur.execute("SELECT Subject_Grade FROM Grades WHERE Subject_Name= %s AND Students_Student_ID= %s AND SchoolYear=%s AND Grading='2nd'",(y[n],ID,SY))
            rows=cur.fetchall()

            if len(rows) < 1:
                null=""
                self.grid_2_copy.SetCellValue(x,2,null)
            else:
                for i in rows:
                    i

                self.grid_2_copy.SetCellValue(x,2,str(i[0]))
            x=x+1
            n=n+1
        n=0
        x=0

        for w in range(0,len(y)):
            cur.execute("SELECT Subject_Grade FROM Grades WHERE Subject_Name= %s AND Students_Student_ID= %s AND SchoolYear=%s AND Grading='3rd'",(y[n],ID,SY))
            rows=cur.fetchall()

            if len(rows) < 1:
                null=""
                self.grid_2_copy.SetCellValue(x,3,null)
            else:
                for i in rows:
                    i

                self.grid_2_copy.SetCellValue(x,3,str(i[0]))
            x=x+1
            n=n+1
        n=0
        x=0

        for w in range(0,len(y)):
            cur.execute("SELECT Subject_Grade FROM Grades WHERE Subject_Name= %s AND Students_Student_ID= %s AND SchoolYear=%s AND Grading='4th'",(y[n],ID,SY))
            rows=cur.fetchall()

            if len(rows) < 1:
                null=""
                self.grid_2_copy.SetCellValue(x,4,null)
            else:
                for i in rows:
                    i

                self.grid_2_copy.SetCellValue(x,4,str(i[0]))
            x=x+1
            n=n+1